[build]
  functions = "netlify/functions"
  publish = "build"

[build.environment]
  # Environment variables for the functions will be set in the Netlify dashboard
  # CICERO_API_KEY = "your-cicero-api-key"

[dev]
  port = 8888
  functionsPort = 8889

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200